// @ts-nocheck
// Auto-generated by FlowGen
import React from 'react';
export default function PageNodePage() {
  return (
    <div className="flowgen-page">
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 flex items-center justify-center p-4">
  <div className="max-w-2xl mx-auto bg-white rounded-xl shadow-lg p-8">
    <div className="text-center mb-6">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">
        Your Component
      </h1>
      <p className="text-gray-600">
        hi
      </p>
    </div>
    
    <div className="space-y-4">
      <div className="p-4 bg-blue-50 rounded-lg">
        <h3 className="font-semibold text-blue-900 mb-2">Feature 1</h3>
        <p className="text-blue-700 text-sm">Generated based on your description</p>
      </div>
      
      <div className="p-4 bg-green-50 rounded-lg">
        <h3 className="font-semibold text-green-900 mb-2">Feature 2</h3>
        <p className="text-green-700 text-sm">Automatically created with AI</p>
      </div>
      
      <div className="p-4 bg-purple-50 rounded-lg">
        <h3 className="font-semibold text-purple-900 mb-2">Feature 3</h3>
        <p className="text-purple-700 text-sm">Ready for customization</p>
      </div>
    </div>
    
    <div className="mt-6 flex justify-center">
      <button className="bg-blue-600 text-white px-6 py-2 rounded-lg font-medium hover:bg-blue-700 transition-colors">
        Get Started
      </button>
    </div>
  </div>
</div>
    </div>
  );
}
